### ISSUE TITLE
Release 0.10

### ISSUE THREAD

**Issue by torkleyy** [slide-rs/specs#244]
This issue lists TODOs for the next release.

* [x] Add more tests
    * [x] In the `world` module ( #254, using doc examples )
    * [x] For the `Merge` system
* [x] Examples
    * [x] Lazy component insertioncomments)
* [x] Book
    * [x] Fix #204 by adding a section to the book (see issue)
    * [x] (Optional) Add chapter about `common` module ( #251 )
* [x] Merge #242 
* [x] Review #230 #239 
* [x] Update changelog

**Comment by torkleyy** [comment]
cc @omni-viral @Xaeroxe

**Comment by torkleyy** [comment]
Taking the book chapter. If somebody would create a benchmark for `RudyStorage` and evaluate it, that would be terrific!

**Comment by Xaeroxe** [comment]
It's gonna be a couple days before I can do anything on here, so I'll revisit this when I have time and grab whatever no one else has grabbed.

**Comment by Xaeroxe** [comment]
I'm taking tests.

**Comment by torkleyy** [comment]
Added #230 to the list.

**Comment by torkleyy** [comment]
@Aceeri Would you be willing to write a transform example using the new Specs features (which you can then also use for Amethyst)?

**Comment by torkleyy** [comment]
Okay, removed transform example, since there's no reason to delay the release any longer. Once #269, #270 and shred PRs are merged, I'll release a new version.

**Comment by kvark** [comment]
looks like everything is set ~~on fire~~ to go?

**Comment by Aceeri** [comment]
Maybe release a patch for `hibitset` and update the version here? Was planning on modifying `specs` a little bit and maybe get rid of `AntiStorage` (replace it with `BitSetNot<<Storage as Join>::Mask>`) for less complexity.

**Comment by torkleyy** [comment]
@kvark @Aceeri @omni-viral 

I think I'm just gonna release a new version now. Open PRs can as far as I see it go into a patch version, and if there is minor breakage I don't see a problem with releasing another version.

**Comment by kvark** [comment]
@torkleyy you could take a chance and remove the `serialize` feature in favor of a simple `serde` features like here  https://github.com/brendanzab/cgmath/blob/3543ac02745c43091d16560a63ca1c346c10bd1f/Cargo.toml#L27

**Comment by torkleyy** [comment]
:tada: Issue is now fully resolved. Thank you so much everybody!
