### ISSUE TITLE
Book improvements 

### ISSUE THREAD

**Issue by Rhuagh** [slide-rs/specs#376]
Collecting all issues pertaining to improving the book here:

- [x] #334 - "The book should probably have chapter dedicated for components that would explain stuff like storing entities in components and using marker components vs "special" entities."
- [x] #333 - Strategies for dealing with sorting entities based on component values
- [x] #332 - Strategies for dealing with entity relationships
- [x] #331 - Troubleshooting section dealing with `no resource with the given id` problems
- [x] #310 - Describe how to retrieve components (not sure this is still relevant, but should be followed up)
- [ ] #327 - Incorporate diagrams from @torkleyy's computer
- [x] #370 Update all occurences of `Fetch`, `FetchMut`, `world.write`, `world.read`
- [x] #397 Describe the `Tracked` feature
- [ ] Describe the `saveload` feature

Some of these issues overlap a fair bit, but there we go.

**Comment by torkleyy** [comment]
@Rhuagh is working on several items of this issue, please comment here if you have interest in fixing one.

**Comment by torkleyy** [comment]
Postponed.

**Comment by Rhuagh** [comment]
Moved remaining items to a separate ticket.
