### ISSUE TITLE
Specs 1.0 roadmap

### ISSUE THREAD

**Issue by torkleyy** [slide-rs/specs#532]
This is the tracking issue for the 1.0 release.

## Alpha phase

**Goal:** Get the API to a level that's supposedly stable and robust.

### Steps

* [ ] Check error handling for consistency
* [ ] Evaluate `System::setup`
    * [ ] How much should we keep? (everything / `Default` only / no automatic setup)
    * [ ] Work out good practices
    * [ ] Look into initialization story in general
* [ ] `RestrictedStorage` (is it useful? intersection with other APIs)
    * [ ] Is it actually useful? How applicable?
    * [ ] With which APIs does it intersect?
    * [ ] Can its uage be improved?
* [ ] Remove `common` module
* [ ] Remove experimental modules / move them out
* [ ] Close, fix or postpone all existing issues
* [ ] Try to cut down on dependencies where appropriate; document public dependencies and stabilize them before the alpha release

### Reflection

* [ ] Summarize all changes
* [ ] Release alpha version & create post

## Beta phase

**Goal:** Fix last inconsistencies / problems reported, improve docs quality and create bigger demo.

### Fixes

* [ ] Plan eight weeks starting with the post for collecting problem reports.
* [ ] Fix bugs, fix problems / close issues which are out of scope; document what is in scope and what isn't.

### Documentation

* [ ] Improve top-level documentation; include only reference-style information and keep all explanations in the book; link to the book when appropriate.
* [ ] Ensure the following items are part of every item (where applicable)
    * [ ] `# Errors` section
    * [ ] `# Panics` section
    * [ ] `# Examples` section

### Demo

* [ ] Create bigger demo with good documentation serving _the_ example, showing best practices, common patterns and general usage
* [ ] Make README example more useful / point to demo

### End of beta phase

* [ ] Release beta version and make another post
* [ ] Help a couple of projects upgrading

## 1.0

* [ ] If nothing goes horribly wrong, release `1.0` and make an announcement.

**Comment by torkleyy** [comment]
These are the major API issues remaining:

* [Discourage custom `System::setup`](https://github.com/slide-rs/specs/issues/525)
* [Make `World` an extension of `Resources`](https://github.com/slide-rs/specs/issues/523)

**Comment by LucioFranco** [comment]
@torkleyy I dont think we want to close this?

**Comment by ldesgoui** [comment]
Considering the multiple breaking changes, it might be worth adding a "Migrating from 1.0" page in the tutorial

**Comment by WaDelma** [comment]
Not to be closed
